// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class PdfPageResponse {
  PdfPageResponse({
    this.page,
    this.path,
  });

  int? page;

  String? path;

  Object encode() {
    return <Object?>[
      page,
      path,
    ];
  }

  static PdfPageResponse decode(Object result) {
    result as List<Object?>;
    return PdfPageResponse(
      page: result[0] as int?,
      path: result[1] as String?,
    );
  }
}

class PdfDocumentResponse {
  PdfDocumentResponse({
    this.pageCount,
    this.pages,
  });

  int? pageCount;

  List<PdfPageResponse?>? pages;

  Object encode() {
    return <Object?>[
      pageCount,
      pages,
    ];
  }

  static PdfDocumentResponse decode(Object result) {
    result as List<Object?>;
    return PdfDocumentResponse(
      pageCount: result[0] as int?,
      pages: (result[1] as List<Object?>?)?.cast<PdfPageResponse?>(),
    );
  }
}

class PdfDocumentRequest {
  PdfDocumentRequest({
    this.path,
  });

  String? path;

  Object encode() {
    return <Object?>[
      path,
    ];
  }

  static PdfDocumentRequest decode(Object result) {
    result as List<Object?>;
    return PdfDocumentRequest(
      path: result[0] as String?,
    );
  }
}

class _FlutterPdfViewApiCodec extends StandardMessageCodec {
  const _FlutterPdfViewApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PdfDocumentRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PdfDocumentResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PdfPageResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PdfDocumentRequest.decode(readValue(buffer)!);
      case 129: 
        return PdfDocumentResponse.decode(readValue(buffer)!);
      case 130: 
        return PdfPageResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterPdfViewApi {
  /// Constructor for [FlutterPdfViewApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterPdfViewApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _FlutterPdfViewApiCodec();

  Future<PdfDocumentResponse> renderPdf(PdfDocumentRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_view_pdf.FlutterPdfViewApi.renderPdf', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PdfDocumentResponse?)!;
    }
  }

  Future<String> getVersion() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_view_pdf.FlutterPdfViewApi.getVersion', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }
}
