// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.github.patou.flutter_view_pdf

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PdfPageResponse (
  val page: Long? = null,
  val path: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PdfPageResponse {
      val page = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val path = list[1] as String?
      return PdfPageResponse(page, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      page,
      path,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PdfDocumentResponse (
  val pageCount: Long? = null,
  val pages: List<PdfPageResponse?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PdfDocumentResponse {
      val pageCount = list[0].let { if (it is Int) it.toLong() else it as Long? }
      val pages = list[1] as List<PdfPageResponse?>?
      return PdfDocumentResponse(pageCount, pages)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pageCount,
      pages,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PdfDocumentRequest (
  val path: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PdfDocumentRequest {
      val path = list[0] as String?
      return PdfDocumentRequest(path)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      path,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object FlutterPdfViewApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PdfDocumentRequest.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PdfDocumentResponse.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PdfPageResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PdfDocumentRequest -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PdfDocumentResponse -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PdfPageResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterPdfViewApi {
  fun renderPdf(request: PdfDocumentRequest): PdfDocumentResponse
  fun getVersion(): String

  companion object {
    /** The codec used by FlutterPdfViewApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterPdfViewApiCodec
    }
    /** Sets up an instance of `FlutterPdfViewApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterPdfViewApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_view_pdf.FlutterPdfViewApi.renderPdf", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PdfDocumentRequest
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.renderPdf(requestArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_view_pdf.FlutterPdfViewApi.getVersion", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getVersion())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
